# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

isEqualCpp <- function(x, y) {
    .Call(`_rpact_isEqualCpp`, x, y)
}

getFisherCombinationCaseKmax2Cpp <- function(tVec) {
    .Call(`_rpact_getFisherCombinationCaseKmax2Cpp`, tVec)
}

getFisherCombinationSizeKmax2Cpp <- function(alpha0Vec, criticalValues, tVec, piValue, caseKmax) {
    .Call(`_rpact_getFisherCombinationSizeKmax2Cpp`, alpha0Vec, criticalValues, tVec, piValue, caseKmax)
}

getFisherCombinationCaseKmax3Cpp <- function(tVec) {
    .Call(`_rpact_getFisherCombinationCaseKmax3Cpp`, tVec)
}

getFisherCombinationSizeKmax3Cpp <- function(alpha0Vec, criticalValues, tVec, piValue, caseKmax) {
    .Call(`_rpact_getFisherCombinationSizeKmax3Cpp`, alpha0Vec, criticalValues, tVec, piValue, caseKmax)
}

getFisherCombinationCaseKmax4Cpp <- function(tVec) {
    .Call(`_rpact_getFisherCombinationCaseKmax4Cpp`, tVec)
}

getFisherCombinationSizeApproximatelyKmax4Cpp <- function(alpha0Vec, criticalValues, tVec, piValue, caseKmax) {
    .Call(`_rpact_getFisherCombinationSizeApproximatelyKmax4Cpp`, alpha0Vec, criticalValues, tVec, piValue, caseKmax)
}

getFisherCombinationCaseKmax5Cpp <- function(tVec) {
    .Call(`_rpact_getFisherCombinationCaseKmax5Cpp`, tVec)
}

getFisherCombinationSizeApproximatelyKmax5Cpp <- function(alpha0Vec, criticalValues, tVec, piValue, caseKmax) {
    .Call(`_rpact_getFisherCombinationSizeApproximatelyKmax5Cpp`, alpha0Vec, criticalValues, tVec, piValue, caseKmax)
}

getFisherCombinationCaseKmax6Cpp <- function(tVec) {
    .Call(`_rpact_getFisherCombinationCaseKmax6Cpp`, tVec)
}

getFisherCombinationSizeApproximatelyKmax6Cpp <- function(alpha0Vec, criticalValues, tVec, piValue, caseKmax) {
    .Call(`_rpact_getFisherCombinationSizeApproximatelyKmax6Cpp`, alpha0Vec, criticalValues, tVec, piValue, caseKmax)
}

getFisherCombinationSizeCpp <- function(kMax, alpha0Vec, criticalValues, tVec, cases) {
    .Call(`_rpact_getFisherCombinationSizeCpp`, kMax, alpha0Vec, criticalValues, tVec, cases)
}

getSimulatedAlphaCpp <- function(kMax, alpha0, criticalValues, tVec, iterations) {
    .Call(`_rpact_getSimulatedAlphaCpp`, kMax, alpha0, criticalValues, tVec, iterations)
}

getFisherCombinationCasesCpp <- function(kMax, tVec) {
    .Call(`_rpact_getFisherCombinationCasesCpp`, kMax, tVec)
}

getDesignFisherTryCpp <- function(kMax, alpha, tolerance, criticalValues, scale, alpha0Vec, userAlphaSpending, method) {
    .Call(`_rpact_getDesignFisherTryCpp`, kMax, alpha, tolerance, criticalValues, scale, alpha0Vec, userAlphaSpending, method)
}

getGroupSequentialProbabilitiesCpp <- function(decisionMatrix, informationRates) {
    .Call(`_rpact_getGroupSequentialProbabilitiesCpp`, decisionMatrix, informationRates)
}

getDesignGroupSequentialPampallonaTsiatisCpp <- function(tolerance, beta, alpha, kMax, deltaPT0, deltaPT1, informationRates, sided, bindingFutility) {
    .Call(`_rpact_getDesignGroupSequentialPampallonaTsiatisCpp`, tolerance, beta, alpha, kMax, deltaPT0, deltaPT1, informationRates, sided, bindingFutility)
}

getSpendingValueCpp <- function(alpha, x, sided, typeOfDesign, gamma) {
    .Call(`_rpact_getSpendingValueCpp`, alpha, x, sided, typeOfDesign, gamma)
}

getDesignGroupSequentialUserDefinedAlphaSpendingCpp <- function(kMax, userAlphaSpending, sided, informationRates, bindingFutility, futilityBounds, tolerance) {
    .Call(`_rpact_getDesignGroupSequentialUserDefinedAlphaSpendingCpp`, kMax, userAlphaSpending, sided, informationRates, bindingFutility, futilityBounds, tolerance)
}

getDesignGroupSequentialAlphaSpendingCpp <- function(kMax, alpha, gammaA, typeOfDesign, sided, informationRates, bindingFutility, futilityBounds, tolerance) {
    .Call(`_rpact_getDesignGroupSequentialAlphaSpendingCpp`, kMax, alpha, gammaA, typeOfDesign, sided, informationRates, bindingFutility, futilityBounds, tolerance)
}

getDesignGroupSequentialDeltaWTCpp <- function(kMax, alpha, sided, informationRates, bindingFutility, futilityBounds, tolerance, deltaWT) {
    .Call(`_rpact_getDesignGroupSequentialDeltaWTCpp`, kMax, alpha, sided, informationRates, bindingFutility, futilityBounds, tolerance, deltaWT)
}

getDesignGroupSequentialPocockCpp <- function(kMax, alpha, sided, informationRates, bindingFutility, futilityBounds, tolerance) {
    .Call(`_rpact_getDesignGroupSequentialPocockCpp`, kMax, alpha, sided, informationRates, bindingFutility, futilityBounds, tolerance)
}

getDesignGroupSequentialOBrienAndFlemingCpp <- function(kMax, alpha, sided, informationRates, bindingFutility, futilityBounds, tolerance) {
    .Call(`_rpact_getDesignGroupSequentialOBrienAndFlemingCpp`, kMax, alpha, sided, informationRates, bindingFutility, futilityBounds, tolerance)
}

getDesignGroupSequentialBetaSpendingCpp <- function(criticalValues, kMax, userAlphaSpending, userBetaSpending, sided, informationRates, bindingFutility, tolerance, typeOfDesign, typeBetaSpending, gammaA, gammaB, alpha, beta) {
    .Call(`_rpact_getDesignGroupSequentialBetaSpendingCpp`, criticalValues, kMax, userAlphaSpending, userBetaSpending, sided, informationRates, bindingFutility, tolerance, typeOfDesign, typeBetaSpending, gammaA, gammaB, alpha, beta)
}

getDesignGroupSequentialUserDefinedBetaSpendingCpp <- function(criticalValues, kMax, userAlphaSpending, userBetaSpending, sided, informationRates, bindingFutility, tolerance, typeOfDesign, gammaA, alpha) {
    .Call(`_rpact_getDesignGroupSequentialUserDefinedBetaSpendingCpp`, criticalValues, kMax, userAlphaSpending, userBetaSpending, sided, informationRates, bindingFutility, tolerance, typeOfDesign, gammaA, alpha)
}

getSimulationSurvivalCpp <- function(designNumber, kMax, sided, criticalValues, informationRates, conditionalPower, plannedEvents, thetaH1, minNumberOfEventsPerStage, maxNumberOfEventsPerStage, directionUpper, allocation1, allocation2, accrualTime, treatmentGroup, thetaH0, futilityBounds, alpha0Vec, pi1Vec, pi2, eventTime, piecewiseSurvivalTime, cdfValues1, cdfValues2, lambdaVec1, lambdaVec2, phi, maxNumberOfSubjects, maxNumberOfIterations, maxNumberOfRawDatasetsPerStage, kappa) {
    .Call(`_rpact_getSimulationSurvivalCpp`, designNumber, kMax, sided, criticalValues, informationRates, conditionalPower, plannedEvents, thetaH1, minNumberOfEventsPerStage, maxNumberOfEventsPerStage, directionUpper, allocation1, allocation2, accrualTime, treatmentGroup, thetaH0, futilityBounds, alpha0Vec, pi1Vec, pi2, eventTime, piecewiseSurvivalTime, cdfValues1, cdfValues2, lambdaVec1, lambdaVec2, phi, maxNumberOfSubjects, maxNumberOfIterations, maxNumberOfRawDatasetsPerStage, kappa)
}

zeroin <- function(f, lower, upper, tolerance, maxIter) {
    .Call(`_rpact_zeroin`, f, lower, upper, tolerance, maxIter)
}

bizero <- function(f, lower, upper, tolerance, maxIter) {
    .Call(`_rpact_bizero`, f, lower, upper, tolerance, maxIter)
}

getCipheredValue <- function(x) {
    .Call(`_rpact_getCipheredValue`, x)
}

